### ISSUE TITLE
Add Shiny to page to show the data as needed

### ISSUE THREAD

**Issue by conatus** [commonknowledge/stopwatch#38]

**Comment by janbaykara** [comment]
So it seems like the ask here is specifically to create a custom embed finder for Shiny apps, so that @HabKadSW can embed Shiny apps in articles.

- [Custom embed finders](https://docs.wagtail.org/en/stable/advanced_topics/embeds.html#custom-embed-finder-classes) are extensions to Wagtail's Rich Text Field featureset. Standard embed finders include youtube URLs -> embeddable video players and things like that.
- [Shiny apps](https://shiny.rstudio.com/) are R language-based visualisation tools with a browser UI that can be embedded into web pages
